### PR TITLE
Removed and ignored all unneeded files and directories

### PR DESCRIPTION
**Pull request by crazykyler005**

### CODE REVIEW

**Comment by crazykyler005** [comment]
@schromya is the setting.json file important at all? Seems like all it's doing is approving the spelling of "cytoscape" so it's not flagged as incorrect by the vscode. This word is never used throughout the codebase so it seems unnecessary to even include the .vscode folder at all.

```
{
    "cSpell.words": [
        "cytoscape"
    ]
}
```

**Comment by schromya** [comment]
> @schromya is the setting.json file important at all? Seems like all it's doing is approving the spelling of "cytoscape" so it's not flagged as incorrect by the vscode. This word is never used throughout the codebase so it seems unnecessary to even include the .vscode folder at all.
> 
> ```
> {
>     "cSpell.words": [
>         "cytoscape"
>     ]
> }
> ```

cystoscope was an old library we were using. We are not using it anymore so this is uneeded.

**Review by schromya — CHANGES_REQUESTED** [review]
* static/ can not not be gitignored bc there is an app/static folder that will be gitignored too. Instead this should be `/static/` so only the static file at the root is gitignored
* migrations folder can be totally deleted (since we’re not using Django’s SQL schema, but should not be gitignored
* All `__init__.py` files need to be put back. They’re blank but they tell django the files are a library. It is considered good practice to keep them. They should also not be gitignored.
* app/static/src/output.css should not be gitignored. When we use `python manage.py rundev` our tailwind package looks at our html files, sees what tailwind classes we’re using and puts the html in output.css (rundev is a custom command I created to make this happen). However, in production on Google Cloud, we use `python manage.py runserver` (you can see this in the docker file). Which does NOT generate output.css so it needs that output.css already generated.

**Comment by crazykyler005** [comment]
> * static/ can not not be gitignored bc there is an app/static folder that will be gitignored too. Instead this should be `/static/` so only the static file at the root is gitignored

I doesn't look like this even needs to be ignored since cached or compressed files that are used to render the site locally is now stored in the /staticfiles/ directory since the `COMPRESS_ROOT` variable was updated two months ago.

> * All `__init__.py` files need to be put back. They’re blank but they tell django the files are a library. It is considered good practice to keep them. They should also not be gitignored.

Ok, I'll remove it from the gitignore but you really don't need them as of python 3.3+ unless you want to make your includes less messy https://www.codingem.com/what-is-init-py-file-in-python/

> * app/static/src/output.css should not be gitignored. When we use `python manage.py rundev` our tailwind package looks at our html files, sees what tailwind classes we’re using and puts the html in output.css (rundev is a custom command I created to make this happen). However, in production on Google Cloud, we use `python manage.py runserver` (you can see this in the docker file). Which does NOT generate output.css so it needs that output.css already generated.

Good to know! I'll add it back but eventually we should probably have a git-action that runs the npx command to generate that file for us instead if for some reason the rundev command was never ran after a change was made that affected the frontend

**Review by schromya — APPROVED** [review]
Looks good to me!

**Pull request merged**
